apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: question-channel-stage2-subscription
  namespace: demo-camelk
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: questions-kafka-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: stage2-knative