apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  namespace: demo-camelk
  name: questions-kafka-channel
spec:
  #numPartitions: 3 testing with 1 for debugging purposes
  numPartitions: 1
  replicationFactor: 1