kind: Template
apiVersion: v1
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      labels:
        app: ${RESOURCE_NAME}
      name: ${RESOURCE_NAME}
    stringData:
      camel.kamelet.jms-amqp-10-source-custom.username: ${SOURCE_USERNAME}
      camel.kamelet.jms-amqp-10-source-custom.password: ${SOURCE_PASSWORD}
      camel.kamelet.jms-amqp-10-sink-custom.username: ${SINK_USERNAME}
      camel.kamelet.jms-amqp-10-sink-custom.password: ${SINK_PASSWORD}      
parameters:
  - name: RESOURCE_NAME
    displayName: Resource Name
    description: The name of the service resource that also matches POD app label.
    required: true
  - name: SOURCE_USERNAME
    displayName: Source Broker Username
    description: The username to use for the connection to Source Broker.
    required: true
  - name: SOURCE_PASSWORD
    displayName: Source Broker Password
    description: The password to use for the connection to source broker
    required: true
  - name: SINK_USERNAME
    displayName: Sink Broker Username
    description: The username to use for the connection to Sink Broker.
    required: true
  - name: SINK_PASSWORD
    displayName: Sink Broker Password
    description: The password to use for the connection to Sink broker
    required: true    
